version: '{build}'
shallow_clone: true
environment:
  matrix:
    - PYTHON: "C:\\Python27"
  PATH: "C:\\Python27;C:\\Python27\\Scripts;%PATH%"
  PYINSTALLER_VERSION: "git+https://github.com/pyinstaller/pyinstaller.git"
install:
  - "pip install --src .. -r requirements.txt"
  - "python -c \"from OpenSSL import SSL; print(SSL.SSLeay_version(SSL.SSLEAY_VERSION))\""
build: off  # Not a C# project
test_script:
  - "py.test -n 4"
after_test:
  - |
    git clone https://github.com/mitmproxy/release.git ..\release
    pip install -e ..\release
    python ..\release\rtool.py -p mitmproxy bdist
  - ps: Get-ChildItem ..\release\dist\*.zip | ForEach { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
deploy:
- provider: FTP
  host: 46.101.230.67:2222
  protocol: sftp
  username: travis
  password:
    secure: +Ousom/XDCLx9+bUjr1mRKepgIzLdqP+clMpoAiPXUysZCDGxODD/7ij4z8GJ3AF
  folder: snapshots
  on:
    branch: master