version: '{build}'
build: off  # Not a C# project

branches:
  except:
    - requires-io-master

environment:
  CI_DEPS: codecov>=2.0.5
  CI_COMMANDS: codecov
  matrix:
    - PYTHON: "C:\\Python36"
      TOXENV: "py36"
      PYINSTALLER: "1"
      WININSTALLER: "1"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python -m pip install --disable-pip-version-check -U pip"
  - "pip install -U tox"

test_script:
  - ps: tox -- --verbose --cov-report=term
  - ps: tox -e cibuild -- build

deploy_script:
  ps: tox -e cibuild -- upload

cache:
  - C:\projects\mitmproxy\release\installbuilder\setup -> .appveyor.yml
  - C:\Users\appveyor\AppData\Local\pip\cache
