version: '{build}'
build: off  # Not a C# project

environment:
  CI_DEPS: codecov>=2.0.5
  CI_COMMANDS: codecov
  matrix:
    - PYTHON: "C:\\Python35"
      TOXENV: "py35"
    - PYTHON: "C:\\Python27"
      TOXENV: "py27"

  SNAPSHOT_HOST:
    secure: NeTo57s2rJhCd/mjKHetXVxCFd3uhr8txnjnAXD1tUI=
  SNAPSHOT_PORT:
    secure: TiJPtg60/edYTH8RnoBErg==
  SNAPSHOT_USER:
    secure: 6yBwmO5gv4vAwoFYII8qjQ==
  SNAPSHOT_PASS:
    secure: LPjrtFrWxYhOVGXzfPRV1GjtZE/wHoKq9m/PI6hSalfysUK5p2DxTG9uHlb4Q9qV

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python -m pip install --disable-pip-version-check -U pip"
  - "pip install -U tox"

test_script:
  - ps: "tox -- --cov netlib --cov mitmproxy --cov pathod"

deploy_script:
  ps: |
    if(
      ($Env:TOXENV -match "py35") -and
      (($Env:APPVEYOR_REPO_BRANCH -match "master") -or ($Env:APPVEYOR_REPO_TAG -match "true"))
      ) {
      pip install -U virtualenv
      .\dev.ps1
      cmd /c "python -u .\release\rtool.py bdist 2>&1"
      python -u .\release\rtool.py upload-snapshot --bdist --wheel
    }

cache:
  - C:\Users\appveyor\AppData\Local\pip\cache

notifications:
  - provider: Slack
    incoming_webhook: https://hooks.slack.com/services/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
