# Ruby
gemAuthor: "BrowserUp"
gemAuthorEmail: "hello@browserup.com"
gemDescription: "A REST client for the browserup-mitmproxy"
gemHomepage: "https://browserup.com"
gemName: "browserup_mitmproxy_client"
gemRequiredRubyVersion: ">= 2.3"
gemSummary: "Client for the BrowserUp MitmProxy, an automated testing swiss army knife"
gemVersion: "1.1"
moduleName: "BrowserupMitmProxy"
appDescription: "BrowserUp MitmProxy Client"
